backend:
  name: github
  repo: Giveth/giveth-landing-page # Path to your Github repository
  branch:  next-version-prototyping # Branch to update

media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "_site/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
